### ISSUE TITLE
objtaglist.pkl is missing

### ISSUE THREAD

**Issue by happygirlzt** [xymou/Align-Voting-Behaviors-with-Public-Statements#1]
Hi there, thank you for your wonderful work and kind sharing! When I tried to run `prepare.py`, it seems `objtaglist.pkl` was missing. I noticed there is a line `tag_list=load_obj('taglist')` in the script, however, I cannot find this file in the given `./code/data` folder. Could you help address it? Thank you very much in advance.

**Comment by xymou** [comment]
Sorry for missing the files. Now they have been uploaded to the ./code/data folder. Thank you for your interest. 😊

**Comment by happygirlzt** [comment]
Great! Thank you for your help! 😊

**Comment by happygirlzt** [comment]
Hi @xymou, sorry to bother you again :( 
In the `prepare_data.py`, there is a line`with open('./data/tags/'+tag[1:-1]+'.json') as f: #json file saving tweets on Twitter platform with specific hashtag` it seems the there is no data is provided under this `./data/tags/` folder. Do we need to prepare the data by ourselves? I noticed that in the README under the `code` folder, you mentioned _Besides, for each hashtag, we need to get tweets with the tag on Twitter platform, to get to know the content the tag expresses. crawl_hashtag_tweets.py is an example to achieve this goal._ The tweet json data is needed for `prepare_nodes` to get obj`node2emb, node2type, node2info, node2year` pkls, I guess if these four obj pkls are provided, maybe we don't need to worry about the tweets json file anymore. Thank you in advance!

**Comment by xymou** [comment]
Hi, sorry for the late reply. Here is the link for the pkl files.
https://www.dropbox.com/scl/fo/b8c9advmrfpl2gkjnnxnh/h?dl=0&rlkey=b7pkw3jdzg7utjurlmeuv5xep
Notice that using only the pkl files instead of original text makes it faster for subsequent training but will not fine-tune the BERT. (BTW, when I was working on this project, I was not familiar with source code of transformers, and I used modules like bert_serving and pytorch_pretrained_bert so the code seems dirty and childish. I guess this repo is not easy to follow. Sorry for it!
